### PR TITLE
Apply quantization noise while only training

### PR DESCRIPTION
**Pull request by qbx2**
This patch should improve encoding performance.
Noise can be turned off using eval().

### CODE REVIEW

**Comment by 1zb** [comment]
Sorry I don't have time to test it currently. But I uploaded my trained models. You find them in [release](https://github.com/1zb/pytorch-image-comp-rnn/releases).

**Comment by qbx2** [comment]
I pushed a commit with updated result, and it looks fine. Check the result, please.

**Comment by qbx2** [comment]
[kodim10.zip](https://github.com/1zb/pytorch-image-comp-rnn/files/1436664/kodim10.zip)

Here is decoded kodim10 image files to update images in README.md.

**Comment by 1zb** [comment]
Good work. Thanks!

**Pull request merged**
